FROM python:latest

WORKDIR /usr/src/app

ARG REPOSITORY_ADDR=""
ARG JENKINS_ID=""
ARG JENKINS_TOKEN=""
ARG JENKINS_ADDR=""
ARG JENKINS_JOB=""
ARG JENKINS_PROTOCOL=""

ENV REPOSITORY_ADDR ${REPOSITORY_ADDR}
ENV JENKINS_ID ${JENKINS_ID}
ENV JENKINS_TOKEN ${JENKINS_TOKEN}
ENV JENKINS_ADDR ${JENKINS_ADDR}
ENV JENKINS_JOB ${JENKINS_JOB}
ENV JENKINS_PROTOCOL ${JENKINS_PROTOCOL}

RUN pip install --upgrade pip
RUN pip install requests python-jenkins

ADD *.py /usr/src/app/

EXPOSE 1542

CMD python3 -u ./mitm_relay.py -r 1542:${REPOSITORY_ADDR}:1542 -s request_check.py
